// Account Categories for SAK EP
const ACCOUNT_CATEGORIES = {
  ASSET: 'ASET',
  LIABILITY: 'KEWAJIBAN',
  EQUITY: 'EKUITAS',
  REVENUE: 'PENDAPATAN',
  EXPENSE: 'BEBAN'
};

// Account Types
const ACCOUNT_TYPES = {
  ASSET: 'ASSET',
  LIABILITY: 'LIABILITY',
  EQUITY: 'EQUITY',
  REVENUE: 'REVENUE',
  EXPENSE: 'EXPENSE'
};

// Member Status
const MEMBER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  WITHDRAWN: 'WITHDRAWN'
};

// Savings Types
const SAVINGS_TYPES = {
  PRINCIPAL: 'Simpanan Pokok',
  MANDATORY: 'Simpanan Wajib',
  VOLUNTARY: 'Simpanan Sukarela'
};

// Loan Status
const LOAN_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  DEFAULTED: 'DEFAULTED',
  CANCELLED: 'CANCELLED'
};

// Repayment Status
const REPAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  LATE: 'LATE'
};

// Transaction Types
const TRANSACTION_TYPES = {
  SAVING_DEPOSIT: 'SAVING_DEPOSIT',
  SAVING_WITHDRAWAL: 'SAVING_WITHDRAWAL',
  LOAN_DISBURSEMENT: 'LOAN_DISBURSEMENT',
  LOAN_REPAYMENT: 'LOAN_REPAYMENT',
  SHU_DISTRIBUTION: 'SHU_DISTRIBUTION',
  ADJUSTMENT: 'ADJUSTMENT'
};

// SHU Status
const SHU_PERIOD_STATUS = {
  OPEN: 'OPEN',
  CALCULATED: 'CALCULATED',
  DISTRIBUTED: 'DISTRIBUTED',
  CLOSED: 'CLOSED'
};

// SHU Allocation Types
const SHU_ALLOCATION_TYPES = {
  JASA_MODAL: 'JASA_MODAL',
  JASA_USAHA: 'JASA_USAHA',
  PENDIDIKAN: 'PENDIDIKAN',
  SOSIAL: 'SOSIAL',
  DANA_CADANGAN: 'DANA_CADANGAN'
};

// Default SHU Allocation Rules
const DEFAULT_SHU_ALLOCATION = {
  JASA_MODAL: 30,      // 30%
  JASA_USAHA: 50,      // 50%
  PENDIDIKAN: 5,       // 5%
  SOSIAL: 5,           // 5%
  DANA_CADANGAN: 10    // 10%
};

module.exports = {
  ACCOUNT_CATEGORIES,
  ACCOUNT_TYPES,
  MEMBER_STATUS,
  SAVINGS_TYPES,
  LOAN_STATUS,
  REPAYMENT_STATUS,
  TRANSACTION_TYPES,
  SHU_PERIOD_STATUS,
  SHU_ALLOCATION_TYPES,
  DEFAULT_SHU_ALLOCATION
};
